(()=>{
 const $=id=>document.getElementById(id),E=window.AnketaEditor;let prepared=null,busy=false;
 const status=s=>$('gh-status').textContent=s;
 const bytes=s=>new TextEncoder().encode(s),base64=a=>{let s='';for(let i=0;i<a.length;i+=8192)s+=String.fromCharCode(...a.slice(i,i+8192));return btoa(s);};
 const hash=async a=>[...new Uint8Array(await crypto.subtle.digest('SHA-1',a))].map(x=>x.toString(16).padStart(2,'0')).join('');
 const blobHash=async a=>{const head=bytes('blob '+a.length+'\0'),data=new Uint8Array(head.length+a.length);data.set(head);data.set(a,head.length);return hash(data);};
 const encode=s=>s.split('/').map(encodeURIComponent).join('/');
 function settings(){const owner=$('gh-owner').value.trim(),repo=$('gh-repo').value.trim(),branch=$('gh-branch').value.trim(),folder=$('gh-folder').value.trim().replace(/^\/+|\/+$/g,''),token=$('gh-token').value.trim(),site=$('gh-site').value.trim();if(!/^[\w.-]+$/.test(owner)||!/^[\w.-]+$/.test(repo)||!branch||!token)throw Error('укажите владельца, репозиторий, ветку и токен.');if(!/^[a-zA-Z0-9_-]+(?:\/[a-zA-Z0-9_-]+)*$/.test(folder))throw Error('укажите отдельную папку, например ankety; корень репозитория не используется.');if(!/^https:\/\//.test(site))throw Error('укажите https-адрес папки анкет на сайте.');const u=new URL(site);if(u.username||u.password||u.search||u.hash)throw Error('адрес сайта должен быть без пароля, параметров и #.');return {owner,repo,branch,folder,token,site:site.replace(/\/?$/,'/')};}
 async function api(c,path,method='GET',body){const response=await fetch(`https://api.github.com/repos/${encodeURIComponent(c.owner)}/${encodeURIComponent(c.repo)}/${path}`,{method,headers:{Accept:'application/vnd.github+json',Authorization:'Bearer '+c.token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});if(!response.ok)throw Error(response.status===401?'токен не принят.':response.status===403?'нет доступа: проверьте права токена и правила организации.':response.status===404?'репозиторий или ветка не найдены, либо токен не имеет доступа.':`гитхаб вернул ошибку ${response.status}. изменения в ветку не отправлены.`);return response.json();}
 async function identity(r){if(r.publicationId)return r.publicationId;const key=E.normalize(r.row[1]);return 'student-'+(await hash(bytes(key))).slice(0,16);}
 async function build(c,old,selected){const zip=new JSZip();E.sharedAssets(zip);const students={...old.students},ids=new Set();
 for(const {r,i} of selected){const id=await identity(r);if(ids.has(id))throw Error('две анкеты имеют одинаковое исходное имя. сначала разделите их в таблице.');ids.add(id);const doc=new DOMParser().parseFromString(E.siteHTML(zip,r,i),'text/html');const own=[];
 doc.querySelectorAll('img[src]').forEach(img=>{const src=img.getAttribute('src');if(src.startsWith('assets/students/')){const name=src.split('/').pop(),path='students/'+id+'/images/'+name;zip.file(path,zip.file(src).async('uint8array'));zip.remove(src);img.setAttribute('src','images/'+name);own.push(path);}else if(src.startsWith('assets/'))img.setAttribute('src','../../'+src);});
 doc.querySelectorAll('[data-fallback]').forEach(img=>{const src=img.getAttribute('data-fallback');if(src.startsWith('assets/'))img.setAttribute('data-fallback','../../'+src);});
 doc.querySelectorAll('link[href],script[src]').forEach(el=>{const attr=el.tagName==='LINK'?'href':'src',src=el.getAttribute(attr);if(src.startsWith('assets/'))el.setAttribute(attr,'../../'+src);});
 doc.querySelector('link[rel=icon]')?.setAttribute('href','../../favicon.svg');
 const path='students/'+id+'/index.html';zip.file(path,'<!doctype html>\n'+doc.documentElement.outerHTML);own.push(path);students[id]={name:r.given+' '+r.family,files:own};}
 const doc=document.implementation.createHTMLDocument('анкеты учеников');doc.documentElement.lang='ru';const meta=doc.createElement('meta');meta.charset='utf-8';doc.head.prepend(meta);const icon=doc.createElement('link');icon.rel='icon';icon.href='./favicon.svg';icon.type='image/svg+xml';doc.head.append(icon);const h=doc.createElement('h1');h.textContent='анкеты учеников';doc.body.append(h);const ul=doc.createElement('ul');for(const [id,r]of Object.entries(students).sort((a,b)=>a[1].name.localeCompare(b[1].name,'ru'))){const li=doc.createElement('li'),a=doc.createElement('a');a.href='students/'+id+'/';a.textContent=r.name;li.append(a);ul.append(li);}doc.body.append(ul);zip.file('index.html','<!doctype html>\n'+doc.documentElement.outerHTML);
 const files=new Map();for(const [path,f]of Object.entries(zip.files)){if(!f.dir)files.set(path,await f.async('uint8array'));}
 const shared=[...files.keys()].filter(x=>x.startsWith('assets/'));const manifest={format:'raven-anketa-site',version:1,students,shared};files.set('catalog.json',bytes(JSON.stringify(manifest,null,2)));return {files,manifest,ids};}
 function validateManifest(m){if(m.format!=='raven-anketa-site'||m.version!==1||!m.students||!Array.isArray(m.shared))throw Error('в папке найден неизвестный каталог. публикация остановлена.');for(const [id,r]of Object.entries(m.students)){if(!/^student-[a-f0-9]{16}$/.test(id)||typeof r.name!=='string'||!Array.isArray(r.files)||r.files.some(p=>!p.startsWith('students/'+id+'/')||p.includes('..')))throw Error('каталог анкет поврежден.');}if(m.shared.some(p=>!p.startsWith('assets/')||p.includes('..')))throw Error('каталог общих файлов поврежден.');}
 function invalidate(){prepared=null;$('gh-review').hidden=true;}
 const remembered=['gh-owner','gh-repo','gh-branch','gh-folder','gh-site'];
 try{const saved=JSON.parse(localStorage.getItem('anketa-github-settings')||'{}');for(const id of remembered)if(typeof saved[id]==='string')$(id).value=saved[id];}catch{}
 function catalogLink(){const raw=$('gh-site').value.trim();$('catalog-link').href=/^https:\/\//i.test(raw)?raw:'../';}
 catalogLink();
 $('github-panel').querySelectorAll('input,select').forEach(el=>el.addEventListener('input',()=>{invalidate();catalogLink();try{localStorage.setItem('anketa-github-settings',JSON.stringify(Object.fromEntries(remembered.map(id=>[id,$(id).value]))));}catch{}}));
 $('gh-prepare').onclick=async()=>{if(busy)return;busy=true;invalidate();$('gh-prepare').disabled=true;try{if(!E.getRecords().length)throw Error('сначала загрузите таблицу или сохраненный проект.');E.flush();const c=settings();status('проверяю репозиторий и готовлю файлы…');const ref=await api(c,'git/ref/heads/'+encode(c.branch)),commit=await api(c,'git/commits/'+ref.object.sha),tree=await api(c,'git/trees/'+commit.tree.sha+'?recursive=1');if(tree.truncated)throw Error('список файлов слишком большой; выберите отдельный репозиторий для анкет.');const remote=new Map(tree.tree.filter(x=>x.type==='blob').map(x=>[x.path,x.sha])),catalog=c.folder+'/catalog.json';let old={format:'raven-anketa-site',version:1,students:{},shared:[]};if(remote.has(catalog)){const blob=await api(c,'git/blobs/'+remote.get(catalog));old=JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(blob.content.replace(/\s/g,'')),ch=>ch.charCodeAt(0))));validateManifest(old);}else if(tree.tree.some(x=>x.path===c.folder||x.path.startsWith(c.folder+'/')))throw Error('эта папка уже содержит файлы без каталога редактора. выберите новую пустую папку, чтобы не перезаписать чужие страницы.');
 const records=E.getRecords(),index=+$('student').value,selected=$('gh-scope').value==='all'?records.map((r,i)=>({r,i})):[{r:records[index],i:index}],built=await build(c,old,selected),changes=[];
 for(const [path,data]of built.files){const full=c.folder+'/'+path,sha=await blobHash(data);if(remote.get(full)!==sha)changes.push({path:full,data,sha});}
 const deletions=[];for(const id of built.ids){for(const path of old.students[id]?.files||[])if(!built.files.has(path)&&remote.has(c.folder+'/'+path))deletions.push(c.folder+'/'+path);}
 const text=selected.map(({r})=>r.given+' '+r.family).join('\n');$('gh-summary').textContent=`${c.owner}/${c.repo} · ${c.branch}\nпапка: ${c.folder}\n${text}\nдобавить или обновить файлов: ${changes.length}\nудалить замененных изображений: ${deletions.length}\nостальные опубликованные анкеты сохраняются.`;
 prepared={c,head:ref.object.sha,tree:commit.tree.sha,changes,deletions,selected,built};$('gh-review').hidden=false;$('gh-publish').disabled=!changes.length&&!deletions.length;status(changes.length||deletions.length?'готово к публикации. проверьте список выше.':'все файлы уже совпадают с опубликованными.');}catch(e){status(e.message);}finally{busy=false;$('gh-prepare').disabled=false;}};
 $('gh-publish').onclick=async()=>{if(busy||!prepared)return;busy=true;$('gh-publish').disabled=true;$('gh-prepare').disabled=true;const p=prepared;try{status('отправляю подготовленные файлы…');const ref=await api(p.c,'git/ref/heads/'+encode(p.c.branch));if(ref.object.sha!==p.head)throw Error('репозиторий изменился. нажмите «проверить и подготовить» еще раз.');const entries=[];for(const [i,f] of p.changes.entries()){status(`отправляю файл ${i+1} из ${p.changes.length}…`);const b=await api(p.c,'git/blobs','POST',{content:base64(f.data),encoding:'base64'});entries.push({path:f.path,mode:'100644',type:'blob',sha:b.sha});}for(const path of p.deletions)entries.push({path,mode:'100644',type:'blob',sha:null});const tree=await api(p.c,'git/trees','POST',{base_tree:p.tree,tree:entries}),commit=await api(p.c,'git/commits','POST',{message:'обновление анкет учеников',tree:tree.sha,parents:[p.head]});await api(p.c,'git/refs/heads/'+encode(p.c.branch),'PATCH',{sha:commit.sha,force:false});const links=$('gh-links');links.replaceChildren();for(const {r}of p.selected){const id=await identity(r);r.publicationId=id;const a=document.createElement('a');a.href=p.c.site+'students/'+id+'/';a.textContent=r.given+' '+r.family;a.target='_blank';a.rel='noopener';links.append(a);}status('файлы отправлены. ссылки заработают после обновления GitHub Pages. сохраните проект редактора.');invalidate();}catch(e){status(e.message);invalidate();}finally{busy=false;$('gh-prepare').disabled=false;}};
 window.AnketaPublisher={build,identity,blobHash,validateManifest};
})();
